"""Minimal database protocols used by domain services."""

from __future__ import annotations

from typing import Any, Protocol


class DatabaseQuery(Protocol):
    """Subset of the SQLAlchemy query API used by current services."""

    def filter(self, *criteria: Any) -> DatabaseQuery: ...

    def order_by(self, *criteria: Any) -> DatabaseQuery: ...

    def offset(self, offset: int) -> DatabaseQuery: ...

    def limit(self, limit: int) -> DatabaseQuery: ...

    def all(self) -> list[Any]: ...

    def first(self) -> Any | None: ...

    def scalar(self) -> Any: ...


class DatabaseSession(Protocol):
    """Transaction and query operations required by domain services."""

    def query(self, *entities: Any) -> DatabaseQuery: ...

    def add(self, instance: Any) -> None: ...

    def delete(self, instance: Any) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def refresh(self, instance: Any) -> None: ...

