"""initial schema baseline

Revision ID: 13dc81aa2d5b
Revises: 
Create Date: 2026-09-09 23:49:16.321594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13dc81aa2d5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='会话标题'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='会话状态：active/archived'),
    sa.Column('capabilities', sa.JSON(), nullable=True, comment='会话默认聊天能力列表：knowledge/practice/web_search；最近一次消息用到的能力自动同步'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='最后活跃时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('course_name', sa.String(length=200), server_default=sa.text("'未分类'"), nullable=False),
    sa.Column('academic_year', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('semester', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='MIME 类型'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='原始文件存储路径（相对 files 目录，如 <document_id>/<filename>）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态：pending/processing/completed/failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息（status=failed 时记录具体 stage 与可读错误）'),
    sa.Column('chapter_count', sa.Integer(), nullable=False, comment='章节数量'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='知识切片数量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='处理完成时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domains',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='科目名称'),
    sa.Column('code', sa.String(length=20), nullable=True, comment='课程代码（如 MATH101）'),
    sa.Column('description', sa.Text(), nullable=True, comment='科目描述'),
    sa.Column('grade', sa.String(length=10), nullable=False, comment='适用年级：大一/大二/大三/大四'),
    sa.Column('semester', sa.String(length=10), nullable=False, comment='适用学期：上/下'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_index('idx_domains_grade', ['grade'], unique=False)
        batch_op.create_index('idx_domains_semester', ['semester'], unique=False)

    op.create_table('exam_records',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('knowledge_combo', sa.Text(), nullable=False, comment='关联知识点 ID 列表（JSON 数组字符串）'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='难度层级：1=概念层, 2=关联层, 3=深层关联'),
    sa.Column('question_type', sa.String(length=50), nullable=True, comment='题目类型：choice/fill/solve'),
    sa.Column('question_text', sa.Text(), nullable=True, comment='题目内容'),
    sa.Column('answer_text', sa.Text(), nullable=True, comment='参考答案'),
    sa.Column('domain', sa.String(length=50), nullable=True, comment='所属领域/科目'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='是否已被使用'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_records', schema=None) as batch_op:
        batch_op.create_index('idx_exam_combo', ['knowledge_combo'], unique=False)
        batch_op.create_index('idx_exam_difficulty', ['difficulty'], unique=False)
        batch_op.create_index('idx_exam_domain', ['domain'], unique=False)

    op.create_table('memory_cursors',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('memory_generation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('layer', sa.String(length=10), nullable=False),
    sa.Column('input_refs', sa.JSON(), nullable=True),
    sa.Column('output_refs', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_l0_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('recorded_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_l0_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_l0_messages_recorded_at_ms'), ['recorded_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_l0_messages_session_id'), ['session_id'], unique=False)

    op.create_table('memory_l1_atoms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('source_message_ids', sa.JSON(), nullable=True),
    sa.Column('scene_name', sa.String(length=200), nullable=True),
    sa.Column('activity', sa.String(length=20), server_default=sa.text("'conversation'"), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('scope', sa.String(length=20), server_default=sa.text("'activity'"), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('timestamps', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_l1_atoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_l1_atoms_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_l1_atoms_updated_at_ms'), ['updated_at_ms'], unique=False)

    op.create_table('quiz_papers',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('session_id', sa.String(length=36), nullable=True, comment='来源会话 ID（可空）'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='试卷标题'),
    sa.Column('document_ids', sa.JSON(), nullable=True, comment='出题依据的文档 ID 列表'),
    sa.Column('document_titles', sa.JSON(), nullable=True, comment='文档文件名列表（冗余存储，避免反查）'),
    sa.Column('requirements', sa.Text(), nullable=True, comment='用户出题需求原文'),
    sa.Column('question_types', sa.JSON(), nullable=True, comment='实际题型列表'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='难度等级：1=基础, 2=进阶, 3=综合'),
    sa.Column('questions_json', sa.Text(), nullable=False, comment='完整试卷 JSON（题目+答案+解析，已校验）'),
    sa.Column('file_path_md', sa.String(length=500), nullable=True, comment='Markdown 导出文件相对路径（quiz_papers/<id>/<title>.md）'),
    sa.Column('file_path_json', sa.String(length=500), nullable=True, comment='JSON 导出文件相对路径（quiz_papers/<id>/<title>.json）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('domain_id', sa.String(length=36), nullable=False, comment='所属科目 ID'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父章节 ID（自引用，NULL 表示顶层章）'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='章节名称'),
    sa.Column('level', sa.Integer(), nullable=False, comment='层级：1=章, 2=节, 3=小节'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('description', sa.Text(), nullable=True, comment='章节描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index('idx_chapters_domain', ['domain_id'], unique=False)
        batch_op.create_index('idx_chapters_parent', ['parent_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='所属会话 ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色：user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('sources', sa.JSON(), nullable=True, comment='引用的知识切片/网页列表：[{id, title, document_id, score, url}]'),
    sa.Column('quiz_paper_id', sa.String(length=36), nullable=True, comment='关联试卷 ID（模拟练习消息），普通消息为 NULL'),
    sa.Column('document_ids', sa.JSON(), nullable=True, comment='用户消息通过 @ 选择的文档 ID 列表；练习模式上下文连贯的回退依据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='发送时间'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='所属文档 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='知识切片标题'),
    sa.Column('chapter', sa.String(length=255), nullable=False, comment='所属章节名称'),
    sa.Column('section', sa.String(length=255), nullable=False, comment='所属小节名称'),
    sa.Column('content', sa.Text(), nullable=False, comment='知识切片内容'),
    sa.Column('source_pages', sa.JSON(), nullable=True, comment='来源页码列表：[1, 2]'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表：["tea", "history"]'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index('idx_document_chunks_document', ['document_id'], unique=False)

    op.create_table('knowledge_catalog',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('chapter_id', sa.String(length=36), nullable=False, comment='所属章节 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='知识点标题'),
    sa.Column('domain', sa.String(length=50), nullable=False, comment='所属领域/科目（冗余字段）'),
    sa.Column('chapter', sa.String(length=100), nullable=True, comment='所属章节名称（冗余字段）'),
    sa.Column('section', sa.String(length=100), nullable=True, comment='所属小节名称（冗余字段）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_catalog', schema=None) as batch_op:
        batch_op.create_index('idx_catalog_chapter', ['chapter_id'], unique=False)
        batch_op.create_index('idx_catalog_domain', ['domain'], unique=False)

    op.create_table('knowledge_content',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('catalog_id', sa.String(length=36), nullable=False, comment='关联知识目录 ID（唯一）'),
    sa.Column('content', sa.Text(), nullable=False, comment='Markdown 格式正文内容'),
    sa.Column('key_points', sa.Text(), nullable=True, comment='要点列表（JSON 数组字符串）'),
    sa.Column('formulas', sa.Text(), nullable=True, comment='公式列表（JSON 数组字符串，LaTeX 格式）'),
    sa.Column('examples', sa.Text(), nullable=True, comment='示例列表（JSON 数组字符串）'),
    sa.Column('difficulty_level', sa.Integer(), nullable=False, comment='难度等级：1=基础, 2=中等, 3=进阶'),
    sa.Column('exam_frequency', sa.Integer(), nullable=False, comment='考试出现频率（用于出题权重）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['catalog_id'], ['knowledge_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id')
    )
    with op.batch_alter_table('knowledge_content', schema=None) as batch_op:
        batch_op.create_index('idx_content_catalog', ['catalog_id'], unique=False)

    op.create_table('knowledge_links',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('source_id', sa.String(length=36), nullable=False, comment='源知识点 ID'),
    sa.Column('target_id', sa.String(length=36), nullable=False, comment='目标知识点 ID'),
    sa.Column('relation_type', sa.String(length=50), nullable=False, comment='关系类型：prerequisite/composable/similar_to/part_of/leads_to/easily_confused'),
    sa.Column('weight', sa.Float(), nullable=False, comment='关联强度（0.0~1.0）'),
    sa.Column('context', sa.Text(), nullable=True, comment='关联上下文说明'),
    sa.Column('is_cross_domain', sa.Boolean(), nullable=False, comment='是否跨领域关联'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', name='uq_link_source_target')
    )
    with op.batch_alter_table('knowledge_links', schema=None) as batch_op:
        batch_op.create_index('idx_links_source', ['source_id'], unique=False)
        batch_op.create_index('idx_links_target', ['target_id'], unique=False)

    op.create_table('knowledge_source',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('catalog_id', sa.String(length=36), nullable=True, comment='关联知识目录 ID（NULL 表示尚未关联）'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='来源文件类型：pdf/ppt/docx/image'),
    sa.Column('source_filename', sa.String(length=255), nullable=True, comment='原始文件名'),
    sa.Column('source_path', sa.String(length=500), nullable=True, comment='文件存储路径'),
    sa.Column('markdown_content', sa.Text(), nullable=True, comment='从原始文件提取的 Markdown 内容'),
    sa.Column('page_range', sa.String(length=50), nullable=True, comment='页码范围（如 1-5, 10）'),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True, comment='内容提取时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['catalog_id'], ['knowledge_catalog.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_source', schema=None) as batch_op:
        batch_op.create_index('idx_source_catalog', ['catalog_id'], unique=False)

    op.create_table('review_records',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键 UUID'),
    sa.Column('catalog_id', sa.String(length=36), nullable=False, comment='关联知识目录 ID'),
    sa.Column('review_count', sa.Integer(), nullable=False, comment='累计复习次数'),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='上次复习时间'),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True, comment='下次复习时间'),
    sa.Column('mastery_level', sa.Integer(), nullable=False, comment='掌握程度：0=未学习, 1=了解, 2=理解, 3=掌握, 4=熟练, 5=精通'),
    sa.Column('incorrect_count', sa.Integer(), nullable=False, comment='累计答错次数'),
    sa.Column('notes', sa.Text(), nullable=True, comment='学习笔记'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['catalog_id'], ['knowledge_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_records', schema=None) as batch_op:
        batch_op.create_index('idx_review_catalog', ['catalog_id'], unique=False)
        batch_op.create_index('idx_review_mastery', ['mastery_level'], unique=False)
        batch_op.create_index('idx_review_next', ['next_review_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_records', schema=None) as batch_op:
        batch_op.drop_index('idx_review_next')
        batch_op.drop_index('idx_review_mastery')
        batch_op.drop_index('idx_review_catalog')

    op.drop_table('review_records')
    with op.batch_alter_table('knowledge_source', schema=None) as batch_op:
        batch_op.drop_index('idx_source_catalog')

    op.drop_table('knowledge_source')
    with op.batch_alter_table('knowledge_links', schema=None) as batch_op:
        batch_op.drop_index('idx_links_target')
        batch_op.drop_index('idx_links_source')

    op.drop_table('knowledge_links')
    with op.batch_alter_table('knowledge_content', schema=None) as batch_op:
        batch_op.drop_index('idx_content_catalog')

    op.drop_table('knowledge_content')
    with op.batch_alter_table('knowledge_catalog', schema=None) as batch_op:
        batch_op.drop_index('idx_catalog_domain')
        batch_op.drop_index('idx_catalog_chapter')

    op.drop_table('knowledge_catalog')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index('idx_document_chunks_document')

    op.drop_table('document_chunks')
    op.drop_table('chat_messages')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index('idx_chapters_parent')
        batch_op.drop_index('idx_chapters_domain')

    op.drop_table('chapters')
    op.drop_table('quiz_papers')
    with op.batch_alter_table('memory_l1_atoms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_l1_atoms_updated_at_ms'))
        batch_op.drop_index(batch_op.f('ix_memory_l1_atoms_session_id'))

    op.drop_table('memory_l1_atoms')
    with op.batch_alter_table('memory_l0_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_l0_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_memory_l0_messages_recorded_at_ms'))

    op.drop_table('memory_l0_messages')
    op.drop_table('memory_generation_logs')
    op.drop_table('memory_cursors')
    with op.batch_alter_table('exam_records', schema=None) as batch_op:
        batch_op.drop_index('idx_exam_domain')
        batch_op.drop_index('idx_exam_difficulty')
        batch_op.drop_index('idx_exam_combo')

    op.drop_table('exam_records')
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_index('idx_domains_semester')
        batch_op.drop_index('idx_domains_grade')

    op.drop_table('domains')
    op.drop_table('documents')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
